using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AMSDemo.Models
{
    public class OPLD
    {
        public int OPLDID { get; set; }        
        public string PAGE_SMT_REC_FLAG { get; set; }
        public string VERSION_NUMBER { get; set; }
        public string PAGE_INF_SRC_TYP_CD { get; set; }
        public string PAGE_MAILBOX { get; set; }
        public string PAGE_PICKUP_DT { get; set; }
        public string PAGE_PICKUP_CC_DT { get; set; }
        public string PAGE_PICKUP_YY_DT { get; set; }
        public string PAGE_PICKUP_MM_DT { get; set; }
        public string PAGE_PICKUP_DD_DT { get; set; }
        public string PAGE_SEQ_NUM { get; set; }
        public string PAGE_SHIPPER_NUMBER { get; set; }
        public string PAGE_SHIPPER_COUNTRY { get; set; }
        public string PAGE_PICKUP_BOOK { get; set; }
        public string PAGE_PICKUP_PAGE { get; set; }
        public string PAGE_PICKUP_BOOK_TYPE { get; set; }
        public string PAGE_VOID_IND { get; set; }
        public string PAGE_VSN_NR { get; set; }
        public string SMT_SEQ_NR { get; set; }
        public string SHIP_PKGING_TYP { get; set; }
        public string SHIP_DOC_IND { get; set; }
        public string SHIP_CONTAINER_TYPE { get; set; }
        public string SHIP_BILL_TERMS { get; set; }
        public string SHIP_PAY_MEDIA_TYPE { get; set; }
        public string SHIP_SHR_3PB_FLG { get; set; }
        public string SHIP_CSGN_3PB_FLG { get; set; }
        public string SHIP_REF_TYP_CD_1 { get; set; }
        public string SHIP_REF_NR_1 { get; set; }
        public string SHIP_REF_TYP_CD_2 { get; set; }
        public string SHIP_REF_NR_2 { get; set; }
        public string SHIP_CWT_IND { get; set; }
        public string SHIP_ADDR_TYPE_1 { get; set; }
        public string SHIP_AC_NR_1 { get; set; }
        public string SHIP_COMP_NA_1 { get; set; }
        public string SHIP_ATTENTION_NAME_1 { get; set; }
        public string SHIP_ADDR_LINE_1_1 { get; set; }
        public string SHIP_ADDR_LINE_2_1 { get; set; }
        public string SHIP_ADDR_LINE_3_1 { get; set; }
        public string SHIP_CITY_NAME_1 { get; set; }
        public string SHIP_STATE_CODE_1 { get; set; }
        public string SHIP_ZIP_CODE_1 { get; set; }
        public string SHIP_COUNTRY_CODE_1 { get; set; }
        public string SHIP_PH_NR_1 { get; set; }
        public string SHIP_ADDR_TYPE_2 { get; set; }
        public string SHIP_AC_NR_2 { get; set; }
        public string SHIP_COMP_NA_2 { get; set; }
        public string SHIP_ATTENTION_NAME_2 { get; set; }
        public string SHIP_ADDR_LINE_1_2 { get; set; }
        public string SHIP_ADDR_LINE_2_2 { get; set; }
        public string SHIP_ADDR_LINE_3_2 { get; set; }
        public string SHIP_CITY_NAME_2 { get; set; }
        public string SHIP_STATE_CODE_2 { get; set; }
        public string SHIP_ZIP_CODE_2 { get; set; }
        public string SHIP_COUNTRY_CODE_2 { get; set; }
        public string SHIP_PH_NR_2 { get; set; }
        public string SHIP_ADDR_TYPE_3 { get; set; }
        public string SHIP_AC_NR_3 { get; set; }
        public string SHIP_COMP_NA_3 { get; set; }
        public string SHIP_ATTENTION_NAME_3 { get; set; }
        public string SHIP_ADDR_LINE_1_3 { get; set; }
        public string SHIP_ADDR_LINE_2_3 { get; set; }
        public string SHIP_ADDR_LINE_3_3 { get; set; }
        public string SHIP_CITY_NAME_3 { get; set; }
        public string SHIP_STATE_CODE_3 { get; set; }
        public string SHIP_ZIP_CODE_3 { get; set; }
        public string SHIP_COUNTRY_CODE_3 { get; set; }
        public string SHIP_PH_NR_3 { get; set; }
        public string SHIP_ADDR_TYPE_4 { get; set; }
        public string SHIP_AC_NR_4 { get; set; }
        public string SHIP_COMP_NA_4 { get; set; }
        public string SHIP_ATTENTION_NAME_4 { get; set; }
        public string SHIP_ADDR_LINE_1_4 { get; set; }
        public string SHIP_ADDR_LINE_2_4 { get; set; }
        public string SHIP_ADDR_LINE_3_4 { get; set; }
        public string SHIP_CITY_NAME_4 { get; set; }
        public string SHIP_STATE_CODE_4 { get; set; }
        public string SHIP_ZIP_CODE_4 { get; set; }
        public string SHIP_COUNTRY_CODE_4 { get; set; }
        public string SHIP_PH_NR_4 { get; set; }
        public string SHIP_ADDR_TYPE_5 { get; set; }
        public string SHIP_AC_NR_5 { get; set; }
        public string SHIP_COMP_NA_5 { get; set; }
        public string SHIP_ATTENTION_NAME_5 { get; set; }
        public string SHIP_ADDR_LINE_1_5 { get; set; }
        public string SHIP_ADDR_LINE_2_5 { get; set; }
        public string SHIP_ADDR_LINE_3_5 { get; set; }
        public string SHIP_CITY_NAME_5 { get; set; }
        public string SHIP_STATE_CODE_5 { get; set; }
        public string SHIP_ZIP_CODE_5 { get; set; }
        public string SHIP_COUNTRY_CODE_5 { get; set; }
        public string SHIP_PH_NR_5 { get; set; }
        public string SHIP_ADDR_TYPE_6 { get; set; }
        public string SHIP_AC_NR_6 { get; set; }
        public string SHIP_COMP_NA_6 { get; set; }
        public string SHIP_ATTENTION_NAME_6 { get; set; }
        public string SHIP_ADDR_LINE_1_6 { get; set; }
        public string SHIP_ADDR_LINE_2_6 { get; set; }
        public string SHIP_ADDR_LINE_3_6 { get; set; }
        public string SHIP_CITY_NAME_6 { get; set; }
        public string SHIP_STATE_CODE_6 { get; set; }
        public string SHIP_ZIP_CODE_6 { get; set; }
        public string SHIP_COUNTRY_CODE_6 { get; set; }
        public string SHIP_PH_NR_6 { get; set; }
        public string SHIP_ADDR_TYPE_7 { get; set; }
        public string SHIP_AC_NR_7 { get; set; }
        public string SHIP_COMP_NA_7 { get; set; }
        public string SHIP_ATTENTION_NAME_7 { get; set; }
        public string SHIP_ADDR_LINE_1_7 { get; set; }
        public string SHIP_ADDR_LINE_2_7 { get; set; }
        public string SHIP_ADDR_LINE_3_7 { get; set; }
        public string SHIP_CITY_NAME_7 { get; set; }
        public string SHIP_STATE_CODE_7 { get; set; }
        public string SHIP_ZIP_CODE_7 { get; set; }
        public string SHIP_COUNTRY_CODE_7 { get; set; }
        public string SHIP_PH_NR_7 { get; set; }
        public string SHIP_ADDR_TYPE_8 { get; set; }
        public string SHIP_AC_NR_8 { get; set; }
        public string SHIP_COMP_NA_8 { get; set; }
        public string SHIP_ATTENTION_NAME_8 { get; set; }
        public string SHIP_ADDR_LINE_1_8 { get; set; }
        public string SHIP_ADDR_LINE_2_8 { get; set; }
        public string SHIP_ADDR_LINE_3_8 { get; set; }
        public string SHIP_CITY_NAME_8 { get; set; }
        public string SHIP_STATE_CODE_8 { get; set; }
        public string SHIP_ZIP_CODE_8 { get; set; }
        public string SHIP_COUNTRY_CODE_8 { get; set; }
        public string SHIP_PH_NR_8 { get; set; }
        public string SHIP_PKG_QTY { get; set; }
        public string SHIP_OCA_IND { get; set; }
        public string SHIP_COMM_RES_IND { get; set; }
        public string SHIP_SVC_LVL { get; set; }
        public string SHIP_SVC_LVL_IND { get; set; }
        public string SHIP_WAYBILL_BRK_NR { get; set; }
        public string SHIP_WAYBILL_PRINT_IND { get; set; }
        public string SHIP_ACC_TYPE_1 { get; set; }
        public string SHIP_ACC_VALUE_1 { get; set; }
        public string SHIP_ACC_VALUE_N_1 { get; set; }
        public string SHIP_ACC_CCY_CD_1 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_1 { get; set; }
        public string SHIP_ACC_TYPE_2 { get; set; }
        public string SHIP_ACC_VALUE_2 { get; set; }
        public string SHIP_ACC_VALUE_N_2 { get; set; }
        public string SHIP_ACC_CCY_CD_2 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_2 { get; set; }
        public string SHIP_ACC_TYPE_3 { get; set; }
        public string SHIP_ACC_VALUE_3 { get; set; }
        public string SHIP_ACC_VALUE_N_3 { get; set; }
        public string SHIP_ACC_CCY_CD_3 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_3 { get; set; }
        public string SHIP_ACC_TYPE_4 { get; set; }
        public string SHIP_ACC_VALUE_4 { get; set; }
        public string SHIP_ACC_VALUE_N_4 { get; set; }
        public string SHIP_ACC_CCY_CD_4 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_4 { get; set; }
        public string SHIP_ACC_TYPE_5 { get; set; }
        public string SHIP_ACC_VALUE_5 { get; set; }
        public string SHIP_ACC_VALUE_N_5 { get; set; }
        public string SHIP_ACC_CCY_CD_5 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_5 { get; set; }
        public string SHIP_ACC_TYPE_6 { get; set; }
        public string SHIP_ACC_VALUE_6 { get; set; }
        public string SHIP_ACC_VALUE_N_6 { get; set; }
        public string SHIP_ACC_CCY_CD_6 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_6 { get; set; }
        public string SHIP_ACC_TYPE_7 { get; set; }
        public string SHIP_ACC_VALUE_7 { get; set; }
        public string SHIP_ACC_VALUE_N_7 { get; set; }
        public string SHIP_ACC_CCY_CD_7 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_7 { get; set; }
        public string SHIP_ACC_TYPE_8 { get; set; }
        public string SHIP_ACC_VALUE_8 { get; set; }
        public string SHIP_ACC_VALUE_N_8 { get; set; }
        public string SHIP_ACC_CCY_CD_8 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_8 { get; set; }
        public string SHIP_ACC_TYPE_9 { get; set; }
        public string SHIP_ACC_VALUE_9 { get; set; }
        public string SHIP_ACC_VALUE_N_9 { get; set; }
        public string SHIP_ACC_CCY_CD_9 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_9 { get; set; }
        public string SHIP_ACC_TYPE_10 { get; set; }
        public string SHIP_ACC_VALUE_10 { get; set; }
        public string SHIP_ACC_VALUE_N_10 { get; set; }
        public string SHIP_ACC_CCY_CD_10 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_10 { get; set; }
        public string SHIP_ACC_TYPE_11 { get; set; }
        public string SHIP_ACC_VALUE_11 { get; set; }
        public string SHIP_ACC_VALUE_N_11 { get; set; }
        public string SHIP_ACC_CCY_CD_11 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_11 { get; set; }
        public string SHIP_ACC_TYPE_12 { get; set; }
        public string SHIP_ACC_VALUE_12 { get; set; }
        public string SHIP_ACC_VALUE_N_12 { get; set; }
        public string SHIP_ACC_CCY_CD_12 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_12 { get; set; }
        public string SHIP_ACC_TYPE_13 { get; set; }
        public string SHIP_ACC_VALUE_13 { get; set; }
        public string SHIP_ACC_VALUE_N_13 { get; set; }
        public string SHIP_ACC_CCY_CD_13 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_13 { get; set; }
        public string SHIP_ACC_TYPE_14 { get; set; }
        public string SHIP_ACC_VALUE_14 { get; set; }
        public string SHIP_ACC_VALUE_N_14 { get; set; }
        public string SHIP_ACC_CCY_CD_14 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_14 { get; set; }
        public string SHIP_ACC_TYPE_15 { get; set; }
        public string SHIP_ACC_VALUE_15 { get; set; }
        public string SHIP_ACC_VALUE_N_15 { get; set; }
        public string SHIP_ACC_CCY_CD_15 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_15 { get; set; }
        public string SHIP_ACC_TYPE_16 { get; set; }
        public string SHIP_ACC_VALUE_16 { get; set; }
        public string SHIP_ACC_VALUE_N_16 { get; set; }
        public string SHIP_ACC_CCY_CD_16 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_16 { get; set; }
        public string SHIP_ACC_TYPE_17 { get; set; }
        public string SHIP_ACC_VALUE_17 { get; set; }
        public string SHIP_ACC_VALUE_N_17 { get; set; }
        public string SHIP_ACC_CCY_CD_17 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_17 { get; set; }
        public string SHIP_ACC_TYPE_18 { get; set; }
        public string SHIP_ACC_VALUE_18 { get; set; }
        public string SHIP_ACC_VALUE_N_18 { get; set; }
        public string SHIP_ACC_CCY_CD_18 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_18 { get; set; }
        public string SHIP_ACC_TYPE_19 { get; set; }
        public string SHIP_ACC_VALUE_19 { get; set; }
        public string SHIP_ACC_VALUE_N_19 { get; set; }
        public string SHIP_ACC_CCY_CD_19 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_19 { get; set; }
        public string SHIP_ACC_TYPE_20 { get; set; }
        public string SHIP_ACC_VALUE_20 { get; set; }
        public string SHIP_ACC_VALUE_N_20 { get; set; }
        public string SHIP_ACC_CCY_CD_20 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_20 { get; set; }
        public string SHIP_ACC_TYPE_21 { get; set; }
        public string SHIP_ACC_VALUE_21 { get; set; }
        public string SHIP_ACC_VALUE_N_21 { get; set; }
        public string SHIP_ACC_CCY_CD_21 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_21 { get; set; }
        public string SHIP_ACC_TYPE_22 { get; set; }
        public string SHIP_ACC_VALUE_22 { get; set; }
        public string SHIP_ACC_VALUE_N_22 { get; set; }
        public string SHIP_ACC_CCY_CD_22 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_22 { get; set; }
        public string SHIP_ACC_TYPE_23 { get; set; }
        public string SHIP_ACC_VALUE_23 { get; set; }
        public string SHIP_ACC_VALUE_N_23 { get; set; }
        public string SHIP_ACC_CCY_CD_23 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_23 { get; set; }
        public string SHIP_ACC_TYPE_24 { get; set; }
        public string SHIP_ACC_VALUE_24 { get; set; }
        public string SHIP_ACC_VALUE_N_24 { get; set; }
        public string SHIP_ACC_CCY_CD_24 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_24 { get; set; }
        public string SHIP_ACC_TYPE_25 { get; set; }
        public string SHIP_ACC_VALUE_25 { get; set; }
        public string SHIP_ACC_VALUE_N_25 { get; set; }
        public string SHIP_ACC_CCY_CD_25 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_25 { get; set; }
        public string SHIP_ACC_TYPE_26 { get; set; }
        public string SHIP_ACC_VALUE_26 { get; set; }
        public string SHIP_ACC_VALUE_N_26 { get; set; }
        public string SHIP_ACC_CCY_CD_26 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_26 { get; set; }
        public string SHIP_ACC_TYPE_27 { get; set; }
        public string SHIP_ACC_VALUE_27 { get; set; }
        public string SHIP_ACC_VALUE_N_27 { get; set; }
        public string SHIP_ACC_CCY_CD_27 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_27 { get; set; }
        public string SHIP_ACC_TYPE_28 { get; set; }
        public string SHIP_ACC_VALUE_28 { get; set; }
        public string SHIP_ACC_VALUE_N_28 { get; set; }
        public string SHIP_ACC_CCY_CD_28 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_28 { get; set; }
        public string SHIP_ACC_TYPE_29 { get; set; }
        public string SHIP_ACC_VALUE_29 { get; set; }
        public string SHIP_ACC_VALUE_N_29 { get; set; }
        public string SHIP_ACC_CCY_CD_29 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_29 { get; set; }
        public string SHIP_ACC_TYPE_30 { get; set; }
        public string SHIP_ACC_VALUE_30 { get; set; }
        public string SHIP_ACC_VALUE_N_30 { get; set; }
        public string SHIP_ACC_CCY_CD_30 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_30 { get; set; }
        public string SHIP_ACC_TYPE_31 { get; set; }
        public string SHIP_ACC_VALUE_31 { get; set; }
        public string SHIP_ACC_VALUE_N_31 { get; set; }
        public string SHIP_ACC_CCY_CD_31 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_31 { get; set; }
        public string SHIP_ACC_TYPE_32 { get; set; }
        public string SHIP_ACC_VALUE_32 { get; set; }
        public string SHIP_ACC_VALUE_N_32 { get; set; }
        public string SHIP_ACC_CCY_CD_32 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_32 { get; set; }
        public string SHIP_ACC_TYPE_33 { get; set; }
        public string SHIP_ACC_VALUE_33 { get; set; }
        public string SHIP_ACC_VALUE_N_33 { get; set; }
        public string SHIP_ACC_CCY_CD_33 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_33 { get; set; }
        public string SHIP_ACC_TYPE_34 { get; set; }
        public string SHIP_ACC_VALUE_34 { get; set; }
        public string SHIP_ACC_VALUE_N_34 { get; set; }
        public string SHIP_ACC_CCY_CD_34 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_34 { get; set; }
        public string SHIP_ACC_TYPE_35 { get; set; }
        public string SHIP_ACC_VALUE_35 { get; set; }
        public string SHIP_ACC_VALUE_N_35 { get; set; }
        public string SHIP_ACC_CCY_CD_35 { get; set; }
        public string RA_SHIP_COD_CSH_ONLY_IND_35 { get; set; }
        public string SHIP_UOM_WGT { get; set; }
        public string SHIP_DIM_WEIGHT { get; set; }
        public string SHIP_DIM_WEIGHT_NUM { get; set; }
        public string SHIP_ACTUAL_WEIGHT { get; set; }
        public string SHIP_ACTUAL_WEIGHT_NUM { get; set; }
        public string SHIP_BILLED_WEIGHT { get; set; }
        public string SHIP_BILLED_WEIGHT_NUM { get; set; }
        public string SHIP_SENDER_NAME { get; set; }
        public string SHIP_CRED_CARD_NR { get; set; }
        public string SHIP_CRED_CARD_EXP_DT { get; set; }
        public string SHIP_INTERNET_USER_ID { get; set; }
        public string SHIP_CRED_CARD_AUTH_NR { get; set; }
        public string SHIP_SHIPPER { get; set; }
        public string SHIP_CONSIGNEE { get; set; }
        public string SHIP_CNSG_SHIP_NR { get; set; }
        public string SHIP_3PB { get; set; }
        public string SHIP_3PB_SHIP_NR { get; set; }
        public string SHIP_FREIGHT { get; set; }
        public string SHIP_FREIGHT_SHIP_NR { get; set; }
        public string SHIP_RLA_NR { get; set; }
        public string SHIP_RLA_SHIP_NR { get; set; }
        public string SHIP_OVS_NR { get; set; }
        public string SHIP_IVS_NR { get; set; }
        public string SHIP_IVS_SHIP_NR { get; set; }
        public string SHIP_HARM_CDE { get; set; }
        public string SHIP_MANF_CTRY_ORIG_CD { get; set; }
        public string SHIP_CUSTM_VAL_S { get; set; }
        public string SHIP_CUSTM_VAL_N { get; set; }
        public string SHIP_GCCN_IND { get; set; }
        public string SHIP_INV_TOTAL_AMT_N { get; set; }
        public string SHIP_EXP_AC_NR { get; set; }
        public string SHIP_EXP_COMP_NA { get; set; }
        public string SHIP_EXP_ATTN_NAME { get; set; }
        public string SHIP_EXP_ADDR_LINE_1 { get; set; }
        public string SHIP_EXP_ADDR_LINE_2 { get; set; }
        public string SHIP_EXP_ADDR_LINE_3 { get; set; }
        public string SHIP_EXP_CITY { get; set; }
        public string SHIP_EXP_STATE_CD { get; set; }
        public string SHIP_EXP_POSTAL_CD { get; set; }
        public string SHIP_EXP_CNTRY_CD { get; set; }
        public string SHIP_IMP_CITY { get; set; }
        public string SHIP_IMP_STATE_CD { get; set; }
        public string SHIP_IMP_POSTAL_CD { get; set; }
        public string SHIP_IMP_CNTRY_CD { get; set; }
        public string SHIP_CLRNCE_PORT { get; set; }
        public string SHIP_SP_NR { get; set; }
        public string SHIP_NR_PKG { get; set; }
        public string SHIP_SVC_TYP_CD { get; set; }
        public string SHIP_CSGN_ADDR_VAL_RES { get; set; }
        public string SHIP_CRNCY_CDE { get; set; }
        public string SHIP_CSGN_VCE_PHN_NRS { get; set; }
        public string SHIP_CSGN_FAX_PHN_NRS { get; set; }
        public string SHIP_DOMEST_INTL_FLAG { get; set; }
        public string SHIP_SOURCE_FLAG { get; set; }
        public string SHIP_IMP_ACC_NR { get; set; }
        public string SHIP_IMP_FLG { get; set; }
        public string SHIP_INV_CURR_CDE { get; set; }
        public string SHIP_ACY_INS_CC { get; set; }
        public string SHIP_ACY_INS_YY { get; set; }
        public string SHIP_ACY_INS_MM { get; set; }
        public string SHIP_ACY_INS_DD { get; set; }
        public string SHIP_ACY_INS_HH { get; set; }
        public string SHIP_ACY_INS_MIN { get; set; }
        public string SHIP_QVIO_DATA_AREA { get; set; }
        public string SHIP_SHR_OPT_IND { get; set; }
        public string SHIP_USI { get; set; }
        public string SHIP_TDPROD_TYP_CDE { get; set; }
        public string AMS_TOKEN { get; set; }
        public string FILLER { get; set; }
        public string SHIP_REQ_ADDR_CLASS { get; set; }
        public string SHIP_REQ_ADDR_ID { get; set; }
        public string SHIP_IA_GCCNNumber { get; set; }
        public string SHIP_CA01_PKUP_PHN_NR { get; set; }
        public string CRA_PDP_Delivery_Token { get; set; }
        public string CRA_PDP_Delivery_NGDW_Start { get; set; }
        public string CRA_PDP_Delivery_NGDW_End { get; set; }
        public string CRA_PDP_Delivery_NGDW_Confidence { get; set; }
        public string CRA_PDP_Delivery_Date_Required { get; set; }
        public string CRA_PDP_PickUp_Token { get; set; }
        public string CRA_PDP_PickUp_NGDW_Start { get; set; }
        public string CRA_PDP_PickUp_NGDW_End { get; set; }
        public string CRA_PDP_PickUp_NGDW_Confidence { get; set; }
        public string CRA_PDP_PickUp_Date_Required { get; set; }
        public string PDP_Replay { get; set; }
        public string PDP_Flags { get; set; }
        public string SHIP_PSI_NR_PCS { get; set; }
        public string SHIP_DSPLY_NAME { get; set; }
        public string ProcessingStatus { get; set; }
        public List<Package> Packages { get; set; }
    }
}

